Repository BRIKEV/express-jsdoc-swagger, pull requests merged in 2020-10, with the labels that each got.

#90 feat: add support for `example` annotations
  README.md
  examples/package.json
  examples/requestBody/withExamples.js
  examples/responses/withExamples.js
  test/transforms/paths/requestBody.test.js
  test/transforms/paths/responses.test.js
  transforms/paths/content.js
  transforms/paths/examples.js
  transforms/paths/index.js
  transforms/paths/requestBody.js
  transforms/paths/responses.js
Labels: enhancement, hacktoberfest-accepted, v1.0.6

#94 docs: add header param example
  examples/package.json
  examples/parameters/headers.js
Labels: documentation, hacktoberfest-accepted, v1.0.6

#93 Form parameters
  examples/package.json
  examples/requestBody/formParameters.js
  package.json
  test/transforms/paths/formParameters.test.js
  transforms/paths/content.js
  transforms/paths/formParams.js
  transforms/paths/index.js
  transforms/paths/parameters.js
  transforms/paths/requestBody.js
Labels: documentation, enhancement, hacktoberfest-accepted, v1.0.6

#96 Extract examples validator value as function - long methods
  package-lock.json
  transforms/paths/requestBody.js
Labels: Code climate, hacktoberfest-accepted

#97 Refactor formParams
  transforms/paths/formParams.js
Labels: Code climate, hacktoberfest-accepted
