Repository BRIKEV/express-jsdoc-swagger, pull requests merged in 2020-06, with the labels that each got.

#12 ci: add more node versions
  .github/workflows/npm-publish.yml
  README.md
Labels: Chore

#20 [refactor] max line function code smell
  transforms/paths/parameters.js
Labels: enhancement

#18 Security schemes
  examples/README.md
  examples/package.json
  examples/security/basic-auth.js
  index.js
  test/transforms/security/index.test.js
  transforms/components/index.js
  transforms/index.js
  transforms/security/index.js
Labels: enhancement

#40 Security configuration
  examples/responses/full-example.js
  test/e2e/parameters/parameters.test.js
  test/transforms/paths/index.test.js
  test/transforms/paths/parameters.test.js
  test/transforms/paths/requestBody.test.js
  test/transforms/paths/responses.test.js
  test/transforms/paths/security.test.js
  test/transforms/paths/tags.test.js
  transforms/paths/index.js
Labels: enhancement

#66 Improve error messages
  test/e2e/errors/errors.test.js
  test/e2e/errors/jsdoc-parameter-error.js
  test/e2e/errors/jsdoc-requestBody-error.js
  test/e2e/errors/jsdoc-response-error.js
  transforms/paths/content.js
  transforms/paths/parameters.js
  transforms/paths/requestBody.js
  transforms/paths/responses.js
  transforms/paths/schema.js
Labels: enhancement, refactor

#71 Create CONTRIBUTING.md
  CONTRIBUTING.md
Labels: Chore, documentation
