Repository BRIKEV/express-jsdoc-swagger, pull requests merged in 2020-05, with the labels that each got.

#4 Create npm-publish
  .github/workflows/npm-publish.yml
Labels: Chore

#5 Refactor tests
  .eslintignore
  .github/workflows/npm-publish.yml
  README.md
  index.js
  test/transforms/paths/index.test.js
  test/transforms/paths/parameters.test.js
  test/transforms/paths/responses.test.js
Labels: enhancement

#11 More examples
  .eslintignore
  examples/README.md
  examples/basic/package.json
  examples/configuration/main.js
  examples/package-lock.json
  examples/package.json
  examples/responses/components.js
  examples/responses/full-example.js
  examples/responses/multiple.js
  examples/responses/simple.js
  examples/utils/logger.js
  index.js
  test/transforms/basic/index.test.js
  test/transforms/components/index.test.js
  test/transforms/tags/index.test.js
  transforms/basic/servers.js
  transforms/components/index.js
  transforms/paths/responses.js
  transforms/tags/index.js
  transforms/utils/setProperty.js
Labels: documentation
